# =========================== GENERAL =========================== #
version: ^project.version^
server:
  port: ${port:8090}
# =========================== SPRING =========================== #
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin@admin123

# =========================== APP =========================== #
app:
  queue:
    name: test